CREATE TABLE `kplus_august` (
  `my_category` varchar(40) DEFAULT NULL,
  `datum` datetime DEFAULT NULL,
  `id` int(11) DEFAULT NULL,
  `code` varchar(40) DEFAULT NULL,
  `name` varchar(400) DEFAULT NULL,
  `amount` int(11) DEFAULT NULL,
  `currency` varchar(10) DEFAULT NULL,
  `formatted_price` varchar(10) DEFAULT NULL,
  `description` text,
  `product_path` varchar(200) DEFAULT NULL,
  `image_path` varchar(200) DEFAULT NULL,
  `thumbnail_image_path` varchar(200) DEFAULT NULL,
  `product_details_path` varchar(200) DEFAULT NULL,
  `manufacturer` varchar(400) DEFAULT NULL,
  `sales_unit_of_measure` varchar(20) DEFAULT NULL,
  `quantity_step` double DEFAULT NULL,
  `min_order_quantity` double DEFAULT NULL,
  `netto_weight_factor` double DEFAULT NULL,
  `sliceable` tinyint(1) DEFAULT NULL,
  `catch_weight` int(11) DEFAULT NULL,
  `has_image` tinyint(1) DEFAULT NULL,
  `requires_deposit_packaging` tinyint(1) DEFAULT NULL,
  `image_s` varchar(200) DEFAULT NULL,
  `image_m` varchar(200) DEFAULT NULL,
  `image_l` varchar(200) DEFAULT NULL,
  `netto_weight` int(11) DEFAULT NULL,
  `contact_person` varchar(100) DEFAULT NULL,
  `contact_person_address` varchar(100) DEFAULT NULL,
  `allergens_statement` text,
  `storage_instruction` text,
  `health_claim` text,
  `additives_statement` text,
  `drained_weight` varchar(20) DEFAULT NULL,
  `active` tinyint(1) DEFAULT NULL,
  `price_unit_of_measure` varchar(20) DEFAULT NULL,
  `statistical_price` varchar(20) DEFAULT NULL,
  `favorite` tinyint(1) DEFAULT NULL,
  `ingredients_statement` text,
  `manufacturer_address` varchar(400) DEFAULT NULL,
  `nutritional_claim` text,
  `origin_statement` text,
  `preparation_instruction` text,
  `serving_suggestion` text,
  `storage_instructions` text,
  `variant_description` text,
  `package_id` int(11) DEFAULT NULL,
  UNIQUE KEY `ui_datumID` (`id`,`datum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
