using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace DTO {
    public class Hrana {
        public global::System.DateTime Datum;
        public int Id;
        public string Code;
        public string Name;
        public global::System.Nullable<int> Amount;
        public string Currency;
        public string FormattedPrice;
        public string Description;
        public string ProductPath;
        public string ImagePath;
        public string ThumbnailImagePath;
        public string ProductDetailsPath;
        public string Manufacturer;
        public string SalesUnitOfMeasure;
        public global::System.Nullable<double> QuantityStep;
        public global::System.Nullable<double> MinOrderQuantity;
        public global::System.Nullable<double> NettoWeightFactor;
        public global::System.Nullable<bool> Sliceable;
        public global::System.Nullable<int> CatchWeight;
        public global::System.Nullable<bool> HasImage;
        public global::System.Nullable<bool> RequiresDepositPackaging;
        public string ImageS;
        public string ImageM;
        public string ImageL;
        public global::System.Nullable<int> NettoWeight;
        public string ContactPerson;
        public string ContactPersonAddress;
        public string AllergensStatement;
        public string StorageInstruction;
        public string HealthClaim;
        public string AdditivesStatement;
        public string DrainedWeight;
        public global::System.Nullable<bool> Active;
        public string PriceUnitOfMeasure;
        public string StatisticalPrice;
        public global::System.Nullable<bool> Favorite;
        public string IngredientsStatement;
        public string ManufacturerAddress;
        public string NutritionalClaim;
        public string OriginStatement;
        public string PreparationInstruction;
        public string ServingSuggestion;
        public string StorageInstructions;
        public string VariantDescription;
    }
}
